### ISSUE TITLE
How to move added items?

### ISSUE THREAD

**Issue by AkosNagy2Epam** [clovett/VirtualCanvas#2]
Hi, the demo app is great to let me know how to add objects to the canvas. But I have looked around in the code and I can not figure out what the best way would be to alter the position of an already added item. Like Canvas.SetLeft(,) would do. Is it even possible?

**Comment by clovett** [comment]
Great point, I've added ability to select a shape with mouse click, then you can drag/drop the selected shape to show you how to move shapes.  You do it through the model (DemoShape) and not through any WPF visuals, because the SpatialIndex has to be able to see these changes and re-index the item.  To enable that I added INotifyPropertyChanged to DemoShape which the SpatialIndex listens to.

**Comment by AkosNagy2Epam** [comment]
Thank you for the fast reply and update of the demo app. It works great and smooth.
I have one last question if you don't mind it. All the elements the demo puts on the VirtualCanvas are simple drawings of shapes. Can we make this work with WPF controls like Image or Button? Or is it limited to simple drawn shapes only?

**Comment by lovettchris** [comment]
Absolutely, the visual can be anything, the only trick is you have to be able to "estimate it's overall bounds" which is provided to the SpatialIndex (via DemoShape "ui model" object). For example, this VirtualCanvas is used under the [DGML Graph Editor](https://learn.microsoft.com/en-us/visualstudio/modeling/map-dependencies-across-your-solutions?view=vs-2022) which allows Nodes and "Groups" which are pretty complex WPF objects.  If you do care about scalability however, I would avoid using XAML DataBinding as much as possible, since it really hurts performance.  With my recent update you could also "esimtate the bounds" then "correct the bounds" when your WPF object gets the final [SizeChanged ](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.control.sizechanged?view=windowsdesktop-7.0) event telling you your ActualWidth and ActualHeight, this will then allow the spatial index to be correct for the new size.  This is even more important for a Visual that can self "expand/collapse" like groups in DGML.

**Comment by clovett** [comment]
I just published a new demo vide that goes into more details on how things work including showing how to add a WPF button on the canvas: https://www.youtube.com/watch?v=8QurCVeC9wc&feature=youtu.be
